### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by JacopKane**
Fix tasknames for Gulp 4

### CODE REVIEW

**Comment by austinpray** [comment]
Fix failing tests?

**Comment by JacopKane** [comment]
Sure will check soon

**Comment by JacopKane** [comment]
Interesting. I could't reproduce travis errors on my local machine and not sure what is the problem, yet.

**Comment by austinpray** [comment]
Travis looks like it's running node 0.11, maybe give that a bump

**Pull request closed without merging**
